In [1]:
import pandas as pd

In [2]:
url = 'http://pt.wikipedia.org/wiki/Lista_de_guerras_por_n%C3%BAmero_de_mortos'

In [3]:
tables = pd.read_html(url)

In [4]:
tables[1]

,Guerra,Mortes,Ano,Localização,Notas
0,Segunda Guerra Mundial,70 000 000–85 000 000,1939–1945,"Global, majoritariamente Europa Ocidental",[1] veja Mortos na Segunda Guerra Mundial
1,Conquistas e invasões mongóis,30 000 000–40 000 000,1206–1368,Leste Europeu e Sibéria,[2][3][4][5] – Exclui as (até) 200 000 000 mor...
2,Guerra dos Três reinos,36 000 000–40 000 000,184–280,China,[6][7]
3,Segunda Guerra Sino-Japonesa,20 000 000–25 000 000,1937–1945,China,[8] Parte da Segunda Guerra Mundial.
4,Conquista Qing da dinastia Ming,25 000 000,1616–1662,China,[9] Também conhecida como transição Ming–Qing
5,Rebelião Taiping,20 000 000–70 000 000,1850–1864,China,[10][11] – número de mortos pode estar subesti...
6,Primeira Guerra Mundial/Grande Guerra,16 000 000–40 000 000+ (a estimativa mais alta...,1914–1918,"Global, majoritariamente Europa Ocidental.",[1] Também conhecida como a Grande Guerra
7,Rebelião de An Lushuan,13 000 000–36 000 000,755–763,China,[12] – número de mortos pode estar subestimado
8,Revolta Dungan,8 000 000–20 000 000,1862-1877,China,NaN
9,Conquistas de Tamerlão,8 000 000–20 000 000,1370–1405,Eurásia,[13][14]

In [5]:
tables[2]

,Guerra,Mortes,Ano,Localização,Notas
0,Guerra Civil Chinesa,8 000 000,1927–1949,China,[15]
1,Guerra Civil Russa,5 000 000–9 000 000,1917–1922,Rússia,[16]
2,Guerras Napoleônicas,3 500 000– 6 000 000,1803–1815,Europa,veja Mortos nas Guerras Napoleônicas
3,Guerra dos Trinta Anos,3 000 000– 11 500 000,1618–1648,Europa,[17]
4,Segunda Guerra do Congo/Guerra Mundial Africana,2 500 000– 5 400 000,1998–2003,África Central,[18][19][20][21]
5,Guerras Religiosas na França,2 000 000– 4 000 000,1562–1598,França,[22] – também conhecida como as Guerras Huguen...
6,Guerra Goguryeo–Sui,2 000 000 pelo menos,598–614,Coreia,[23] – Forças coreanas e mortes civis não estã...
7,Conquistas de Shaka Zulu,2 000 000,1816–1828,África do Sul,[24]
8,Guerra da Coreia,1 200 000,1950–1953,Coreia,[25]
9,Cerco de Jerusalém,1 100 000,73,Israel,NaN
10,Revolução Mexicana,1 000 000– 2 000 000,1910–1920,Mexico,[26]
11,Guerra Irã-Iraque/Primeira Guerra do Golfo,1 000 000,1980–1988,Oriente Médio,[27]
12,Guerra Imjin,1 000 000,1592–1598,Coreia,[28]
13,Guerra Civil da Nigéria,1 000 000,1967–1970,Nigéria,NaN
14,Guerra Afegã-Soviética,957 865– 1 622 865,1979–1989,Afeganistão,[29][30]
15,"Conquistas de Maomé II, o Conquistador",873 000,1451–1481,Eurásia,[31]
16,Guerra dos Sete Anos,868 000– 1 400 000,1756–1763,"Europa, Índia e América do Norte",[32][33]
17,Guerra do Vietnã/Segunda Guerra da Indochina,800 000– 3 800 000,1955–1975,Vietnã,[34][35][36]
18,Guerra Civil da Etiópia,400 000- 1 579 000,1974-1991,Etiópia,1 milhão destas mortes foram causadas pela fom...